#Numpy Assignment


Problem Statement:

Consider yourself to be Sam who is a data scientist. He has been invited as a guest lecturer at a college to take a session on numpy.



Tasks to be performed:

1.	Initialize a numpy array of 5*5 dimensions with all the values to be 0


In [85]:
import numpy as np
np.zeros((5, 5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [86]:
np.full((5,5),0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

2.	Create a numpy array with initial value 10 and final 100 with an interval of 5 between each value

In [87]:
np.arange(start=10, stop=101, step=5)

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

3.	Create a 2-D array with values (10,20,30,40,50,60) and set the dimension to be 2*3

a.	Print the number of elements in the array

In [88]:
a = np.array([10, 20, 30,40, 50, 60]).reshape(2, 3)

a



array([[10, 20, 30],
       [40, 50, 60]])

In [89]:
elements=[]
for i in a:
    for j in i:
        elements.append(j)

elements




[10, 20, 30, 40, 50, 60]

b.	Get the data-type of the array

In [90]:
a.dtype

dtype('int32')

4.	Create first numpy array with values (1,2,3). Create second numpy array with values (4,5,6). Perform simple arithmetic operations on these two numpy arrays:

a.	Addition
b.	Subtraction
c.	Multiplication
d.	Division


In [91]:
#a.	Addition
a=np.array([1,2,3])
b=np.array([4,5,6])



In [92]:
a+b

array([5, 7, 9])

In [93]:
a-b

array([-3, -3, -3])

In [94]:
a*b

array([ 4, 10, 18])

In [95]:
a/b

array([0.25, 0.4 , 0.5 ])

In [96]:
np.add(a,b)

array([5, 7, 9])

In [97]:
np.subtract(a,b)

array([-3, -3, -3])

In [98]:
np.multiply(a,b)

array([ 4, 10, 18])

In [99]:
np.divide(a,b)

array([0.25, 0.4 , 0.5 ])

5.	Create a numpy array with values 10-90 and set the shape to be 3*3

In [100]:
s=np.arange(10,91,10).reshape(3,3)
s


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [101]:
s[0:1,:]

array([[10, 20, 30]])

In [102]:
s[1:2,:]

array([[40, 50, 60]])

In [103]:
s[2,1]

80

a.	Extract only the 3rd column from the numpy array

In [104]:
s[:,2:]

array([[30],
       [60],
       [90]])

b.	Extract only the 2nd row from the numpy array

In [105]:
s[1:2,:]

array([[40, 50, 60]])

In [106]:
s[1:2]

array([[40, 50, 60]])

c.	Extract those cells at the intersection of first two rows and first two columns


In [107]:
s[0:2,0:2]

array([[10, 20],
       [40, 50]])